### ISSUE TITLE
compilation error - cannot find -lSceKernel_stub

### ISSUE THREAD

**Issue by futurepr0n** [ArkSource/vitaAudio#2]
Hi! Tried to compile the project, have had success with other Vita demos, but for some reason, the -lSceKernel_stub could not be found.

` vagrant@vagrant:~/dev/vitaAudio$ make
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/main.o src/main.c
src/main.c: In function 'main':
src/main.c:56:2: warning: implicit declaration of function 'dir_create' [-Wimplicit-function-declaration]
  dir_create( "ux0:/data/vitaAudio/" );
  

arm-vita-eabi-ld -r -b binary -o resources/sprites/img_bg.o resources/sprites/img_bg.png
arm-vita-eabi-ld -r -b binary -o resources/sprites/img_btn.o resources/sprites/img_btn.png
arm-vita-eabi-ld -r -b binary -o resources/sprites/img_btnp.o resources/sprites/img_btnp.png
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/util/memory.o src/vitaAudio/ogg/util/memory.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/util/float-to-int16.o src/vitaAudio/ogg/util/float-to-int16.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/util/decode-frame.o src/vitaAudio/ogg/util/decode-frame.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/stb_vorbis.o src/vitaAudio/ogg/decode/stb_vorbis.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/setup.o src/vitaAudio/ogg/decode/setup.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/seek.o src/vitaAudio/ogg/decode/seek.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/packet.o src/vitaAudio/ogg/decode/packet.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/io.o src/vitaAudio/ogg/decode/io.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/decode.o src/vitaAudio/ogg/decode/decode.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/decode/crc32.o src/vitaAudio/ogg/decode/crc32.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/version.o src/vitaAudio/ogg/api/version.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/seek-tell.o src/vitaAudio/ogg/api/seek-tell.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/read-int16.o src/vitaAudio/ogg/api/read-int16.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/read-float.o src/vitaAudio/ogg/api/read-float.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/open-file.o src/vitaAudio/ogg/api/open-file.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/open-callbacks.o src/vitaAudio/ogg/api/open-callbacks.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/open-buffer.o src/vitaAudio/ogg/api/open-buffer.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/info.o src/vitaAudio/ogg/api/info.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/ogg/api/close.o src/vitaAudio/ogg/api/close.c
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/wav/wav.o src/vitaAudio/wav/wav.c
src/vitaAudio/wav/wav.c: In function 'ParseWaveHeader':
src/vitaAudio/wav/wav.c:23:36: warning: value computed is not used [-Wunused-value]
  _getLong(pucCodecAddr, &readbyte) - 4; /* skip rLen, RIFF chunk length */

arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/buffer/buffer.o src/vitaAudio/buffer/buffer.c
src/vitaAudio/buffer/buffer.c: In function 'CreateBuffer':
src/vitaAudio/buffer/buffer.c:20:76: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
 ileBuffer->lock < 0 ) { printf( "ERROR: sceKernelCreateLwMutex 0x%08x\n", ret ); return ret; }
                                                                     ^
src/vitaAudio/buffer/buffer.c: In function 'DeleteBuffer':
src/vitaAudio/buffer/buffer.c:31:33: warning: passing argument 1 of 'sceKernelDeleteMutex' makes integer from pointer without a cast [-Wint-conversion]
  ret   = sceKernelDeleteMutex ( &fileBuffer->lock );
                                 ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:512:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelDeleteMutex(SceUID mutexid);
     ^~~~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c: In function 'SetBufferData':
src/vitaAudio/buffer/buffer.c:52:22: warning: passing argument 1 of 'sceKernelLockMutex' makes integer from pointer without a cast [-Wint-conversion]
  sceKernelLockMutex( &fileBuffer->lock, 1, 0 );
                      ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:538:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelLockMutex(SceUID mutexid, int lockCount, unsigned int *timeout);
     ^~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c:56:26: warning: passing argument 1 of 'sceKernelUnlockMutex' makes integer from pointer without a cast [-Wint-conversion]
   sceKernelUnlockMutex ( &fileBuffer->lock, 1 );
                          ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:566:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelUnlockMutex(SceUID mutexid, int unlockCount);
     ^~~~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c:74:24: warning: passing argument 1 of 'sceKernelUnlockMutex' makes integer from pointer without a cast [-Wint-conversion]
  sceKernelUnlockMutex( &fileBuffer->lock, 1 );
                        ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:566:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelUnlockMutex(SceUID mutexid, int unlockCount);
     ^~~~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c: In function 'GetBufferData':
src/vitaAudio/buffer/buffer.c:86:23: warning: passing argument 1 of 'sceKernelLockMutex' makes integer from pointer without a cast [-Wint-conversion]
  sceKernelLockMutex ( &fileBuffer->lock, 1, 0 );
                       ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:538:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelLockMutex(SceUID mutexid, int lockCount, unsigned int *timeout);
     ^~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c:90:25: warning: passing argument 1 of 'sceKernelUnlockMutex' makes integer from pointer without a cast [-Wint-conversion]
   sceKernelUnlockMutex( &fileBuffer->lock, 1 );
                         ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:566:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelUnlockMutex(SceUID mutexid, int unlockCount);
     ^~~~~~~~~~~~~~~~~~~~
src/vitaAudio/buffer/buffer.c:109:24: warning: passing argument 1 of 'sceKernelUnlockMutex' makes integer from pointer without a cast [-Wint-conversion]
  sceKernelUnlockMutex( &fileBuffer->lock, 1 );
                        ^
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/buffer/buffer.h:5,
                 from src/vitaAudio/buffer/buffer.c:4:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:566:5: note: expected 'SceUID {aka int}' but argument is of type 'SceUID * {aka int *}'
 int sceKernelUnlockMutex(SceUID mutexid, int unlockCount);
     ^~~~~~~~~~~~~~~~~~~~
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable   -c -o src/vitaAudio/vitaAudio.o src/vitaAudio/vitaAudio.c
src/vitaAudio/vitaAudio.c: In function 'readWavHeader':
src/vitaAudio/vitaAudio.c:46:47: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 )  { printf( "sceIoLseek() 0x%08x\n", ret ); goto term; }
                                               ^
src/vitaAudio/vitaAudio.c:50:46: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 ) { printf( "sceIoLseek() 0x%08x\n", ret ); goto term; }
                                              ^
src/vitaAudio/vitaAudio.c:56:47: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 )  { printf( "sceIoLseek() 0x%08x\n", ret ); goto term; }
                                               ^
src/vitaAudio/vitaAudio.c:65:55: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
   if ( ret < 0 ) { printf ( "ERROR: sceIoRead () 0x%08x\n", ret ); goto term; }
                                                       ^
src/vitaAudio/vitaAudio.c:73:63: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 )  { printf( "ERROR: _sceParseWaveHeader() 0x%08x\n", ret ); goto term; }
                                                               ^
src/vitaAudio/vitaAudio.c:77:46: warning: format '%x' expects argument of type  unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 ) { printf( "sceIoLseek() 0x%08x\n", ret ); goto term; }
                                              ^
src/vitaAudio/vitaAudio.c: In function 'soundThread':
src/vitaAudio/vitaAudio.c:122:66: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( portId < 0 )  { printf( "Error: sceAudioOutOpenPort() 0x%08x\n",portId ); goto term; }
                                                                  ^
src/vitaAudio/vitaAudio.c:125:91: warning: passing argument 3 of 'sceAudioOutSetVolume' from incompatible pointer type [-Wincompatible-pointer-types]
 lume( portId, (SCE_AUDIO_VOLUME_FLAG_L_CH | SCE_AUDIO_VOLUME_FLAG_R_CH), vol );
                                                                          ^~~
In file included from src/vitaAudio/vitaAudio.c:6:0:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/audioout.h:115:5: note: expected  int *' but argument is of type 'int32_t * {aka long int *}'
 int sceAudioOutSetVolume(int port, int ch, int *vol);
     ^~~~~~~~~~~~~~~~~~~~
src/vitaAudio/vitaAudio.c:147:63: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
    if ( ret < 0 ) { printf ( "Error: sceAudioOutOutput() 0x%08x\n",ret ); break; }
                                                               ^
src/vitaAudio/vitaAudio.c:153:30: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
    printf ( "currentCount = %u\n", GetBufferCurrentCount( audioHandler->fileBuffer ) );
                              ^
src/vitaAudio/vitaAudio.c:161:65: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 ) { printf( "Error: sceAudioOutReleasePort() 0x%08x\n",ret ); goto term; }
                                                                 ^
src/vitaAudio/vitaAudio.c: In function 'readThread':
src/vitaAudio/vitaAudio.c:195:62: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'uint32_t {aka long unsigned int}' [-Wformat=]
      if ( capacity < 0 ) { printf( "ERROR: sceIoRead () 0x%08x\n", capacity ); goto term; }
                                                              ^
src/vitaAudio/vitaAudio.c:214:57: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
      if ( ret < 0 ) { printf( "ERROR: sceIoRead () 0x%08x\n", ret ); goto term; }
                                                         ^
src/vitaAudio/vitaAudio.c:238:59: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
      if ( count < 0 ) { printf( "ERROR: sceIoRead () 0x%08x\n", ret ); goto term; }
                                                           ^
src/vitaAudio/vitaAudio.c:251:47: warning: passing argument 2 of 'SetBufferData' from incompatible pointer type [-Wincompatible-pointer-types]
      SetBufferData( audioHandler->fileBuffer, buf, count * 4 );
                                               ^~~
In file included from src/vitaAudio/vitaAudio.h:9:0,
                 from src/vitaAudio/vitaAudio.c:9:
src/vitaAudio/buffer/buffer.h:26:9: note: expected 'uint8_t * {aka unsigned char *}' but argument is of type 'int16_t * {aka short int *}'
 int32_t SetBufferData    ( FileBuffer* fileBuffer, uint8_t* data, uint32_t setSize );
         ^~~~~~~~~~~~~
src/vitaAudio/vitaAudio.c: In function 'InitializeAudio':
src/vitaAudio/vitaAudio.c:304:63: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 )         { printf("ERROR: CreateBuffer () 0x%08x\n", ret); goto error; }
                                                               ^
src/vitaAudio/vitaAudio.c:309:15: warning: passing argument 2 of 'sceKernelCreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
               soundThread,
               ^~~~~~~~~~~
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/vitaAudio.h:5,
                 from src/vitaAudio/vitaAudio.c:9:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:135:8: note: expected 'SceKernelThreadEntry {aka int (*)(unsigned int,  void *)}' but argument is of type 'int32_t (*)(uint32_t,  void *) {aka long int (*)(long unsigned int,  void *)}'
 SceUID sceKernelCreateThread(const char *name, SceKernelThreadEntry entry, int initPriority,
        ^~~~~~~~~~~~~~~~~~~~~
src/vitaAudio/vitaAudio.c:327:15: warning: passing argument 2 of 'sceKernelCreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
               readThread,
               ^~~~~~~~~~
In file included from /usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/processmgr.h:20:0,
                 from src/vitaAudio/vitaAudio.h:5,
                 from src/vitaAudio/vitaAudio.c:9:
/usr/local/vitasdk/arm-vita-eabi/include/psp2/kernel/threadmgr.h:135:8: note: expected 'SceKernelThreadEntry {aka int (*)(unsigned int,  void *)}' but argument is of type 'int32_t (*)(uint32_t,  void *) {aka long int (*)(long unsigned int,  void *)}'
 SceUID sceKernelCreateThread(const char *name, SceKernelThreadEntry entry, int initPriority,
        ^~~~~~~~~~~~~~~~~~~~~
src/vitaAudio/vitaAudio.c: In function 'LoadOgg':
src/vitaAudio/vitaAudio.c:392:57: warning: passing argument 2 of 'vorbis_open_callbacks' makes pointer from integer without a cast [-Wint-conversion]
  handle   = vorbis_open_callbacks( streaming_callbacks, audioHandler->fileHandle, options, &error );
                                                         ^~~~~~~~~~~~
In file included from src/vitaAudio/vitaAudio.c:11:0:
src/vitaAudio/ogg/ogg.h:227:18: note: expected 'void *' but argument is of type 'SceUID {aka int}'
 extern vorbis_t *vorbis_open_callbacks(
                  ^~~~~~~~~~~~~~~~~~~~~
src/vitaAudio/vitaAudio.c: In function 'LoadWav':
src/vitaAudio/vitaAudio.c:442:52: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  if ( ret < 0 ) { printf("ERROR: readHeader() 0x%08x\n", ret); goto term; }
                                                    ^
src/vitaAudio/vitaAudio.c:451:54: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
   if ( ret < 0 ) { printf( "ERROR: sceIoRead () 0x%08x\n", ret ); goto term; }
                                                      ^
src/vitaAudio/vitaAudio.c: In function 'PlayAudio':
src/vitaAudio/vitaAudio.c:473:72: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  ( ret < 0 ) { printf("Error: [readThread]sceKernelStartThread 0x%08x\n", ret); goto term; }
                                                                     ^
src/vitaAudio/vitaAudio.c:475:74: warning: format '%x' expects argument of type 'unsigned int', but argument 2 has type 'int32_t {aka long int}' [-Wformat=]
  ret < 0 ) { printf( "Error: [soundThread]sceKernelStartThread 0x%08x\n", ret ); goto term; }
                                                                     ^
src/vitaAudio/vitaAudio.c:478:1: warning: label 'error' defined but not used [-Wunused-label]
 error:
 ^~~~~
arm-vita-eabi-gcc -Wl,-q -Wall -O3 -std=c99 -Wno-unused-variable -Wno-unused-but-set-variable src/main.o resources/sprites/img_bg.o resources/sprites/img_btn.o resources/sprites/img_btnp.o src/vitaAudio/ogg/util/memory.o src/vitaAudio/ogg/util/float-to-int16.o src/vitaAudio/ogg/util/decode-frame.o src/vitaAudio/ogg/decode/stb_vorbis.o src/vitaAudio/ogg/decode/setup.o src/vitaAudio/ogg/decode/seek.o src/vitaAudio/ogg/decode/packet.o src/vitaAudio/ogg/decode/io.o src/vitaAudio/ogg/decode/decode.o src/vitaAudio/ogg/decode/crc32.o src/vitaAudio/ogg/api/version.o src/vitaAudio/ogg/api/seek-tell.o src/vitaAudio/ogg/api/read-int16.o src/vitaAudio/ogg/api/read-float.o src/vitaAudio/ogg/api/open-file.o src/vitaAudio/ogg/api/open-callbacks.o src/vitaAudio/ogg/api/open-buffer.o src/vitaAudio/ogg/api/info.o src/vitaAudio/ogg/api/close.o src/vitaAudio/wav/wav.o src/vitaAudio/buffer/buffer.o src/vitaAudio/vitaAudio.o -lvita2d -lSceKernel_stub -lSceGxm_stub -lSceSysmodule_stub -lSceCtrl_stub -lScePgf_stub -lSceCommonDialog_stub -lfreetype -lpng -ljpeg -lz -lm -lc -lSceDisplay_stub -lSceTouch_stub -lSceAudio_stub -lSceAudiodec_stub -o bin/VitaAudio.elf
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/bin/ld: cannot find -lSceKernel_stub
collect2: error: ld returned 1 exit status
make: *** [bin/VitaAudio.elf] Error 1 `

My path is set properly,

/usr/local/vitasdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

**Comment by futurepr0n** [comment]
Looks like changing -lSceKernel_stub to -lSceLibKernel_stub did the trick - however I am getting another error:

main.c:(.text.startup+0x16): undefined reference to `dir_create'

IS there a specical prequisite needed to use dir create?

**Comment by futurepr0n** [comment]
Hey - I was able to substitute the dir_create("path") for sceIoMkdir("path", 0777) - but the app although compiles and will come up to load, and create the Dir in ux0:/ as verified in VitaShell - unfortunately however on load it crashes immediately. Not a whole lot of info is out there on the error codes that pop up, I was hoping you might be able to offer me a bit of extra help! Anychance we could connect online - I would be happy to set aside any time you can make to be available, and would even compensate you for your help! 

Really appreciate it! Thanks.

**Comment by readlnh** [comment]
@futurepr0n have you solved the problem?
